<?php

namespace Fwk\Core\Components\UrlRewriter;

use Fwk\Di\ClassDefinition;
use Symfony\Component\HttpFoundation\Request;
/**
 * Test class for ResultTypeService.
 * Generated by PHPUnit on 2013-10-07 at 00:23:59.
 */
class UrlRewriterDescriptorAppTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Fwk\Core\Application
     */
    protected $app;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $service = new UrlRewriterService();
        
        $services = new \Fwk\Di\Container();
        $services->set(
            'requestMatcher', 
            new ClassDefinition(
                'Fwk\\Core\\Components\\RequestMatcher\\RequestMatcher'
            ), 
            true
        );
        $services->set('viewHelper', new \Fwk\Core\Components\ViewHelper\ViewHelperService(), true);
        $services->set('resultTypeService', new \Fwk\Core\Components\ResultType\ResultTypeService(), true);
        $services->set('urlRewriter', $service, true);
        $services->set('helloActionService', function($name) {
            return 'hello '. $name;
        });
        
        $desc = new \Fwk\Core\Components\Descriptor\Descriptor(
                TEST_RESOURCES_DIR . DIRECTORY_SEPARATOR . 'Descriptor' .
                DIRECTORY_SEPARATOR . 'app_test.xml'
        );
        $desc->import(TEST_RESOURCES_DIR . DIRECTORY_SEPARATOR . 'Descriptor' .
                DIRECTORY_SEPARATOR . 'app_test2.xml');
        
        $desc->iniProperties(TEST_RESOURCES_DIR . DIRECTORY_SEPARATOR . 'Descriptor' .
                DIRECTORY_SEPARATOR . 'config-one.ini');
        
        $this->app = $desc->execute('testApp', $services);
    }
    
    public function testRoutesFromDescriptor()
    {
        $req = Request::create('/hello/joe');
        $result = $this->app->run($req);
        
        $this->assertEquals('hello joe', $result->getContent());
    }
}
