<?php

namespace Fwk\Core\Components\ViewHelper;

use Symfony\Component\HttpFoundation\Request;

class TestHelper2 extends AbstractViewHelper implements ViewHelper
{
    public function execute(array $arguments)
    {
        return 'testHelper';
    }
}

/**
 * Test class for ResultTypeService.
 * Generated by PHPUnit on 2013-10-07 at 00:23:59.
 */
class ViewHelperApplicationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Fwk\Core\Application
     */
    protected $app;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $service = new ViewHelperService();
        $service->add('test', new TestHelper2());
        
        $app = \Fwk\Core\Application::factory('testApp')
                ->addListener(new \Fwk\Core\Components\RequestMatcher\RequestMatcherListener('requestMatcher'))
                ->addListener(new ViewHelperListener('viewHelperService'));
        $app['TestAction'] = '+'. TEST_RESOURCES_DIR . DIRECTORY_SEPARATOR . 'viewhelper_template.php';
        
        $app->getServices()->set(
            'requestMatcher', 
            new \Fwk\Core\Components\RequestMatcher\RequestMatcher(),
            true
        );
        $app->getServices()->set('viewHelperService', $service, true);
        
        $this->object = $app;
    }
    
    public function testActionDataHasViewhelper()
    {
        $req = Request::create('/TestAction.action');
        $result = $this->object->run($req);
        
        $this->assertInstanceOf('\Symfony\Component\HttpFoundation\Response', $result);
        $this->assertEquals('testHelper', $result->getContent());
    }
    
    public function testWrongService()
    {
        
        $service = new ViewHelperService();
        $service->add('test', new TestHelper2());
        
        $app = \Fwk\Core\Application::factory('testApp')
                ->addListener(new \Fwk\Core\Components\RequestMatcher\RequestMatcherListener('requestMatcher'))
                ->addListener(new ViewHelperListener('requestMatcher'));
        $app['TestAction'] = '+'. TEST_RESOURCES_DIR . DIRECTORY_SEPARATOR . 'viewhelper_template.php';
        
        $app->getServices()->set(
            'requestMatcher', 
            new \Fwk\Core\Components\RequestMatcher\RequestMatcher(),
            true
        );
        $app->getServices()->set('viewHelperService', $service, true);
        
        $this->object = $app;
        
        $req = Request::create('/TestAction.action');
        
        $this->setExpectedException('Fwk\Core\Components\ViewHelper\Exception');
        $this->object->run($req);
    }
}
