<?php

namespace Fwk\Core;


/**
 * Test class for Context.
 * Generated by PHPUnit on 2013-10-06 at 22:15:10.
 */
class ContextTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Context
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Context(\Symfony\Component\HttpFoundation\Request::create('/'));
    }

    public function testParentContext()
    {
        $this->assertFalse($this->object->hasParent());
        $this->assertInstanceOf('Fwk\Core\Context', $newCtx = $this->object->newParent());
        $this->assertNotEquals($newCtx, $this->object);
        $this->assertEquals($newCtx->getParent(), $this->object);
        $this->assertTrue($newCtx->hasParent());
    }
    
    public function testExecutedState()
    {
        $this->assertFalse($this->object->isExecuted());
        $this->object->setResult('test');
        $this->assertTrue($this->object->isExecuted());
        $this->assertEquals(Context::STATE_EXECUTED, $this->object->getState());
    }
    
     public function testErrorState()
    {
        $this->assertFalse($this->object->isError());
        $this->object->setError('test error');
        $this->assertTrue($this->object->isError());
        $this->assertEquals(Context::STATE_ERROR, $this->object->getState());
        $this->assertEquals('test error', $this->object->getError());
    }
}

?>
