<?php

namespace Fwk\Core;


/**
 * Test class for Exception.
 * Generated by PHPUnit on 2012-07-29 at 23:06:26.
 */
class DescriptorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Descriptor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Descriptor(__DIR__.'/TestApp/fwk.xml');
    }

    public function testAppDetails()
    {
        $this->assertEquals("TestApp", $this->object->getId());
        $this->assertEquals("1.0-dev", $this->object->getVersion());
    }
    
    public function testDescritorErrors()
    {
        $this->setExpectedException("\Fwk\Core\Exception");
        $this->object = new Descriptor(__DIR__.'/TestApp/fwk-nonexist.xml');
    }
    
    public function testActions()
    {
        $this->assertFalse($this->object->hasAction('Inexistant'));
        $this->assertTrue($this->object->hasAction('Hello'));
    }
    
    public function testListeners()
    {
        $listeners = $this->object->getListeners();
        $this->assertTrue(is_array($listeners));
        $this->assertEquals('Fwk\Core\CoreListener', $listeners[0]['class']);
    }
}
