<?php

namespace Fwk\Core;

/**
 * Test class for Object.
 * Generated by PHPUnit on 2012-06-07 at 00:26:06.
 */
class ObjectTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Object;
    }

    /**
     */
    public function testGet() {
        $this->assertNull($this->object->get('not-set'));
        $this->assertTrue($this->object->get('not-set-but-default', true));
        
        $this->object->set('this-is-set', 'value');
        $this->assertEquals('value', $this->object->get('this-is-set'));
    }
    
    /**
     */
    public function testGetWithClosure() {
        $this->object->set('di', function() {
            
            return new \stdClass();
        });
        
        $first = $this->object->get('di');
        $this->assertInstanceOf('\stdClass', $first);
        $this->assertEquals($first, $this->object->get('di'));
    }

    /**
     */
    public function testRawGet() {
        $func = function() {
            
            return new \stdClass();
        };
        
        $this->object->set('di', $func);
        $this->assertEquals($func, $this->object->rawGet('di'));
    }

    /**
     */
    public function testDelete() {
        $this->assertNull($this->object->get('not-set'));
        $this->object->set('not-set', 'value');
        $this->object->delete('not-set');
        $this->assertNull($this->object->get('not-set'));
        $this->assertTrue($this->object->get('not-set', true));
    }
}
