<?php

namespace Fwk\Core\Components\ResultType;

/**
 * Test class for ResultTypeService.
 * Generated by PHPUnit on 2013-10-07 at 00:23:59.
 */
class ResultTypeServiceTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ResultTypeService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ResultTypeService();
    }

   
    /**
     */
    public function testAddRemoveType() {
        $type = new JsonResultType();
        $this->assertFalse($this->object->hasType('testType'));
        $this->assertEquals($this->object, $this->object->addType('testType', $type));
        $this->assertTrue($this->object->hasType('testType'));
        $this->assertEquals($type, $this->object->getType('testType'));
        $this->assertEquals($this->object, $this->object->removeType('testType'));
        $this->assertFalse($this->object->hasType('testType'));
        
        $this->setExpectedException('Fwk\Core\Components\ResultType\Exception');
        $this->object->getType('unregisteredType');
    }
}
