<?php

namespace Fwk\Core\Action;


/**
 * Test class for IncludeActionProxy.
 * Generated by PHPUnit on 2013-10-06 at 21:00:47.
 */
class IncludeActionProxyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IncludeActionProxy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IncludeActionProxy(TEST_RESOURCES_DIR . DIRECTORY_SEPARATOR . 'test_incl_proxy.php');
    }

    /**
     */
    public function testExecute() {
        $this->assertEquals('success_include', $this->object->execute($this->getApp(), $this->getContext()));
    }

    /**
     */
    public function testInvalidInclude() {
        $this->setExpectedException('Fwk\Core\Exception');
        $this->object = new IncludeActionProxy('/path/not/exists/test');
        $this->object->execute($this->getApp(), $this->getContext());
    }
    
    /**
     */
    public function testEmptyFilepath() {
        $this->setExpectedException('\InvalidArgumentException');
        $this->object = new IncludeActionProxy('');
        $this->object->execute($this->getApp(), $this->getContext());
    }
    
    public function testServicesAndContextShortcuts() {
        $app = $this->getApp();
        $ctx = $this->getContext();
        $this->object->execute($app, $ctx);
        $this->assertEquals($app->getServices(), $this->object->getServices());
        $this->assertEquals($ctx, $this->object->getContext());
    }
    
    protected function getApp() {
        return \Fwk\Core\Application::factory('testApp');
    }
    
    protected function getContext() {
        $req = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
        return new \Fwk\Core\Context($req);
    }
}
