<?php

namespace Fwk\Core\Action;


/**
 * Test class for ProxyFactory.
 * Generated by PHPUnit on 2013-10-06 at 21:25:34.
 */
class ProxyFactoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ProxyFactory
     */
    protected $object;

    /**
     */
    public function testIncludeFactory() {
        $this->assertInstanceOf('Fwk\Core\Action\IncludeActionProxy', ProxyFactory::factory('+/path/to/include/test'));
    }
    
    /**
     */
    public function testWrongStringShortcut() {
        $this->setExpectedException('Fwk\Core\Exception');
        ProxyFactory::factory('this should be wrong');
    }
    
    /**
     */
    public function testWrongShortcut() {
        $this->setExpectedException('Fwk\Core\Exception');
        ProxyFactory::factory(array('not', 'supported'));
    }

}