<?php

namespace Fwk\Core\Action;


/**
 * Test class for ServiceControllerActionProxy.
 * Generated by PHPUnit on 2013-10-06 at 21:17:48.
 */
class ServiceControllerActionProxyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ServiceControllerActionProxy
     */
    protected $object;

     protected function getApp() {
        return \Fwk\Core\Application::factory('testApp');
    }
    
    protected function getContext() {
        $req = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
        return new \Fwk\Core\Context($req);
    }
    
    /**
     */
    public function testEmptyServiceName() {
        $this->setExpectedException('\InvalidArgumentException');
        $this->object = new ServiceControllerActionProxy('', '');
    }
    
}